language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly
  - 1.27.1

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

before_script:
  - bash scripts/config.sh

script:
  - bash scripts/ci.sh

branches:
  except:
    - master