language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - windows
  - linux
  - osx
matrix:
  allow_failures:
    - rust: 
      - nightly
      - beta
script:
  - cargo build
  - cargo test
