[package]
name = "backup-rs"
version = "0.1.0"
authors = ["Gabriel Dos Ramos Albo <dosramosgabriel@gmail.com>"]

[dependencies]
clap = {version = "~2.32.0", features = ["yaml"]}
env_logger = "0.5.12"
libc = "0.2.43"
log = "0.4.3"
yansi = "0.4.*"