[package]
name = "backup-rs"
version = "0.1.0"
authors = ["Gabriel Dos Ramos Albo <dosramosgabriel@gmail.com>"]

[dependencies]
chrono = {version = "0.4.5", features = ["serde"]}
clap = {version = "~2.32.0", features = ["yaml"]}
env_logger = "0.5.12"
libc = "0.2.43"
log = "0.4.3"
serde = "1.0.71"
serde_derive = "1.0.71"
yansi = "0.4.*"
